Carapacik/swagger_parser

swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart, swagger_parser/lib/src/parser/parser.dart, swagger_parser/lib/src/utils/utils.dart, swagger_parser/test/generator/data_classes_test.dart
The branch contains the following fixes:
1. In swagger v2 generation, the body annotation was previously generated with the name as string parameter like this:
`@Body('name')` which breaks the generated code because the body annotation does not accept a string parameter. It is now generated as `@Body()`. #53
2. Added support for multiline description comment. Previously a description string of "First line\nNext line" would generate a comment for the first line only, now every line will be commented. #54
3. Fixed default value for enums passed as query parameters. Previosly the generated code was `@Query('unit') Unit unit = CELSIUS` but this is invalid in dart syntax, therefore enums default values are now generated as follows: `@Query('unit') Unit unit = Unit.celsius` #56
4. Fixed the …
=> fixes on enum generation, multiline comments support and swagger v2 body params

swagger_parser/CHANGELOG.md, swagger_parser/README.md, swagger_parser/example/pubspec.yaml, swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart, swagger_parser/pubspec.yaml, swagger_parser/test/generator/data_classes_test.dart
Updated `retrofit_generator` dependency to [7.0.7](https://github.com/trevorwang/retrofit.dart/releases/tag/7.0.7) and consequently removed unused `.toJson()` generated methods in enums
=> updated retrofit dependency to v7.0.7

swagger_parser/lib/src/utils/type_utils.dart
Hey @Carapacik and thanks for a great package!
In this super small patch PR, I'm trying to fix duplicate field names in integer-based enums (provided by Open-API definition JSON). For example, if we have a model defined like this:
```json
"Foo": { "enum": [ -1, 0, 1, 2 ], "type": "number" },
```
The package will code generate a model like this:
```dart
@JsonEnum()
enum Foo {
@JsonValue(-1)
value1, // <--- Error, duplicated field.
@JsonValue(0)
value0,
@JsonValue(1)
value1, // <--- Error, duplicated field.
@JsonValue(2)
value2;
num toJson() => _$FooEnumMap[this]!;
}
```
And in this PR package will generate a proper model like this:
```dart
@JsonEnum()
enum Foo {
@JsonValue(-1)
valueMinus1, // <--- Yey! No errors here.
@JsonValue(0)
value0,
@JsonValue(1)
value1, // <--- And no errors here. …
```
=> fix: fixes negative number values in integer enums

swagger_parser/lib/src/utils/case_utils.dart
To match effective dart: DO capitalize acronyms and abbreviations longer than two letters like words.
https://dart.dev/effective-dart/style#do-capitalize-acronyms-and-abbreviations-longer-than-two-letters-like-words
Example:
```json
{
"openapi": "3.1.0",
"components": {
"schemas": {
"HTTPValidationError": {
"type": "object",
"title": "HTTPValidationError"
},
"DeviceFromDB": {
"type": "object",
"title": "DeviceFromDB"
},
"IOPort": {
"type": "object",
"title": "IOPort"
},
"HrvSampleRMSSD": {
"type": "object",
"title": "HrvSampleRMSSD"
},
"HrvSampleSDNNFromDB": {
"type": "object",
"title": "HrvSampleSDNNFromDB"
}
}
}
}
```
Before:
After (recommended by effective dart):
=> Fix groupping words for acronyms and abbreviations

swagger_parser/CHANGELOG.md, swagger_parser/lib/src/generator/models/replacement_rule.dart, swagger_parser/lib/src/parser/parser.dart, swagger_parser/lib/src/utils/case_utils.dart, swagger_parser/pubspec.yaml
```json
"$ref": "#/components/schemas/HrvSampleRMSSD-Input"
```
Before:
`hrv_sample_rmss_d_input_dto.dart`
```dart
class HrvSampleRmssDInput
```
After:
`hrv_sample_rmssd_input.dart`
```dart
class HrvSampleRmssdInput
```
```yaml
enums_to_json: true
replacement_rules:
- pattern: "$"
replacement: "DTO"
```
Before:
```dart
@JsonEnum()
enum UploadTypeDto {
@JsonValue(0)
value0,
@JsonValue(1)
value1;
integerDTO toJson() => _$UploadTypeDtoEnumMap[this]!;    // <-- error
}
```
After:
```dart
@JsonEnum()
enum UploadTypeDto {
@JsonValue(0)
value0,
@JsonValue(1)
value1;
int toJson() => _$UploadTypeDtoEnumMap[this]!;
}
```
```yaml
enums_to_json: true
replacement_rules:
- pattern: "$"
replacement: "DTO"
```
Before:
```dart
@JsonSerializable()
class HttpValidationErrorDto {
const …
```
=> Fixes for replacement rules and case utils

swagger_parser/lib/src/parser/parser.dart, swagger_parser/lib/src/utils/type_utils.dart
OpenApi:
```json
"/api/bells/pagination": {
"get": {
"summary": "Read Bells Pagination",
"operationId": "read_bells_pagination_api_bells_pagination_get",
"parameters": [
{
"required": false,
"schema": {
"$ref": "#/components/schemas/SortOrder",
"default": "asc"
},
"name": "sort_order",
"in": "query"
}
],
"responses": {
"200": {
"description": "Successful Response",
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/Page_BellInDb_"
}
}
}
}
}
}
}
```
Before:
```dart
@GET('/api/bells/pagination')
Future<PageBellInDb> readBellsPaginationApiBellsPaginationGet({
@Query('sort_order') SortOrder sortOrder = asc, // <-- error
});
```
After:
```dart
@GET('/api/bells/pagination')
Future<PageBellInDb> readBellsPaginationApiBellsPaginationGet({
@Query('sort_order') SortOrder …
```
=> Support of default values for ref enum types

swagger_parser/lib/src/parser/parser.dart
OpenApi:
```json
"/api/bells/pagination": {
"get": {
"tags": [
"bell"
],
"summary": "Read Bells Pagination",
"description": "API получения звонков с учетом пагинции.",
"operationId": "read_bells_pagination_api_bells_pagination_get",
"parameters": [
{
"required": false,
"schema": {
"allOf": [
{
"$ref": "#/components/schemas/TimetableBellSortBy"
}
]
},
"name": "sort_by",
"in": "query"
},
{
"required": false,
"schema": {
"anyOf": [
{
"$ref": "#/components/schemas/SortOrder"
}
]
},
"name": "sort_order",
"in": "query"
}
]
}
},
```
Before:
```dart
@GET('/api/bells/pagination')
Future<PageBellInDb> readBellsPaginationApiBellsPaginationGet({
@Query('sort_by') Object? sortBy,
@Query('sort_order') Object? sortOrder,
});
```
After:
```dart
@GET('/api/bells/pagination')
Future<PageBellInDb> …
```
=> Type support in one-element allOf, anyOf and oneOf

swagger_parser/CHANGELOG.md, swagger_parser/README.md, swagger_parser/example/swagger_parser.yaml, swagger_parser/lib/src/config/yaml_config.dart, swagger_parser/lib/src/generator/fill_controller.dart, swagger_parser/lib/src/generator/generator.dart, swagger_parser/lib/src/generator/models/programming_language.dart, swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart, swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart, swagger_parser/lib/src/generator/templates/kotlin_retrofit_client_template.dart, swagger_parser/lib/src/utils/type_utils.dart, swagger_parser/test/generator/data_classes_test.dart
Adds an unknown value for all enums to maintain backward compatibility when adding new values on the backend. https://github.com/Carapacik/swagger_parser/issues/106
Support String values with spaces for enums. https://github.com/Carapacik/swagger_parser/issues/127
=> Unknown enum value

swagger_parser/lib/src/generator/models/universal_request.dart, swagger_parser/lib/src/parser/parser.dart, swagger_parser/test/parser/requests_test.dart, swagger_parser/test/parser/schemas/basic_requests.2.0.json
I added another check in the parametersV2 method so that if there is a content type which is not multipart or form url encoded it is added to the request.
For example, I would expect the following swagger:
```json
{
"swagger": "2.0",
"info": {
"description": "",
"version": "",
"title": "Test swagger"
},
"host": "localhost:8081",
"basePath": "/",
"tags": [
{
"name": "Tests",
"description": "Test Controller"
}
],
"paths": {
"/test": {
"patch": {
"tags": [
"Tests"
],
"description": "Description",
"operationId": "operationId",
"consumes": [
"application/json-patch+json"
],
"produces": [
"application/json"
],
"parameters": [],
"responses": {
"200": {
"description": "Success"
}
}
}
}
},
"definitions": {}
}
```
to generate the following dart code:
```dart
@RestApi()
abstract class TestsClient { …
```
=> fix: getting first available content type for parametersV2 method

README.md, swagger_parser/CHANGELOG.md, swagger_parser/README.md, swagger_parser/example/.gitignore, swagger_parser/example/build.yaml, swagger_parser/example/pubspec.yaml, swagger_parser/example/swagger_parser.yaml, swagger_parser/lib/src/config/yaml_config.dart, swagger_parser/lib/src/generator/fill_controller.dart, swagger_parser/lib/src/generator/generator.dart, swagger_parser/lib/src/generator/models/json_serializer.dart, swagger_parser/lib/src/generator/models/programming_language.dart, swagger_parser/lib/src/generator/templates/dart_dart_mappable_dto_template.dart, swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart, swagger_parser/lib/src/generator/templates/dart_import_dto_template.dart, swagger_parser/lib/src/parser/parser.dart, swagger_parser/lib/src/utils/utils.dart, swagger_parser/pubspec.yaml, swagger_parser/test/generator/data_classes_test.dart, swagger_parser/test/parser/data_classses_test.dart, swagger_parser/test/parser/schemas/enum_class.json
With this issue I add the support for dart_mappable as json_serializer.
[`dart_mappable`](https://pub.dev/packages/dart_mappable), is a library for json serialization and immutable data structures, it is like `freezed` but for our use case is by far better than it (I think in general but this is pretty subjective).
- I transformed `freezed` boolean field with an enum called `JsonSerializer` that allow to understand inside the code which kind of serializer should be used. So the definition inside `swagger_parser.yaml` change in this way: 
```diff
- schema_path: schemas/openapi.json
root_client_name: ApiMicroservice
-   freezed: true
+   jsonSerializer: "freezed"
put_in_folder: true
put_in_folder: true
replacement_rules: []
```
- Obviously, the code that allows you to generate the models …
=> Add support for an another json serializer called `dart_mappable`

swagger_parser/lib/src/parser/parser.dart, swagger_parser/pubspec.yaml
Fixes issue: https://github.com/Carapacik/swagger_parser/issues/147
=> fix: Path-level parameters no longer cause crash.

swagger_parser/CHANGELOG.md, swagger_parser/README.md, swagger_parser/lib/src/config/yaml_config.dart, swagger_parser/lib/src/generator/generator.dart, swagger_parser/lib/src/parser/parser.dart
Sometimes it is useful to skip some parameters.
If tags contain special characters, an invalid client will be generated.
@Carapacik Hi, I have added the changelog of 1.15.0 and recreated create a PR with latest code. :)
=> Skip parameters and Remove tag special characters

swagger_parser/lib/src/config/config_processor.dart
Currently if the schemeUrl is like  `http://api.example.com/swagger/v1/swagger.json` the saved file will become `swaggerswagger.json.json`. This PR fix the file name to `swagger.json`.
=> Fix file name from schemeUrl

swagger_parser/CHANGELOG.md, swagger_parser/README.md, swagger_parser/example/swagger_parser.yaml, swagger_parser/lib/src/config/swp_config.dart, swagger_parser/lib/src/generator/config/generator_config.dart, swagger_parser/lib/src/generator/generator/fill_controller.dart, swagger_parser/lib/src/generator/model/programming_language.dart, swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart, swagger_parser/lib/src/parser/model/universal_request_type.dart, swagger_parser/pubspec.yaml, swagger_parser/test/generator/rest_clients_test.dart
=> #208 - Support dart retrofit 4.1.0 @Extras parameter option

swagger_parser/lib/src/parser/parser/open_api_parser.dart
I addresses the issue [#235](https://github.com/Carapacik/swagger_parser/issues/235) where model file names conflict if different paths use the same property key.
The generated code should distinguish between the data properties of /foo and /bar responses.
Only one Data model is created for both responses.
Modified the open_api_parser.dart file to increment object names when duplicate type names are found.
Added a check for duplicate type names and incremented the object name if a duplicate is detected.
Thank you for considering this PR. 
I look forward to your feedback!
Thank you.
=> fix same poperty name confliction

swagger_parser/CHANGELOG.md, swagger_parser/lib/src/generator/templates/dart_root_client_template.dart, swagger_parser/pubspec.yaml, swagger_parser/test/e2e/tests/basic/additional_properties_class.2.0/expected_files/rest_client.dart, swagger_parser/test/e2e/tests/basic/basic_requests.2.0/expected_files/rest_client.dart, swagger_parser/test/e2e/tests/basic/basic_requests.3.0/expected_files/rest_client.dart, swagger_parser/test/e2e/tests/corrector/expected_files/rest_client.dart, swagger_parser/test/e2e/tests/enum_member_names/expected_files/rest_client.dart, swagger_parser/test/e2e/tests/multipart_request_properties/expected_files/rest_client.dart, swagger_parser/test/e2e/tests/multipart_request_with_ref/expected_files/rest_client.dart, swagger_parser/test/e2e/tests/nullable_types/expected_files/rest_client.dart, swagger_parser/test/e2e/tests/request_unnamed_types/expected_files/rest_client.dart, swagger_parser/test/generator/root_client_test.dart
Sometimes, developers specify the version used in the application. It’s also useful to add a request header like `X-API-Version: 1.0.0`.
```json
{
"openapi": "3.0.0",
"info": {
"version": "1.0.0"
}
}
```
```dart
final client = RestClient(dio);
// 1.0.0
print(RestClient.version);
client.someApi.getRequest(
extras: { 
'custom-header': { 
'X-API-Version': '${RestClient.version}' 
}
}
);
```
=> Add Open API version number to root client

swagger_parser/README.md, swagger_parser/lib/src/config/swp_config.dart, swagger_parser/lib/src/generator/config/generator_config.dart, swagger_parser/lib/src/generator/generator/fill_controller.dart, swagger_parser/lib/src/generator/model/programming_language.dart, swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
I suggest adding the "RequestOptions" transfer using the "@DioOptions" annotation, as this is a very important part of Dio and will allow transferring CancelToken, onReceiveProgress, etc. to requests. I need to be able to cancel requests, but now, in order to transfer, for example, CancelToken, I need to write it manually, and when regenerating it will be erased and I will have to write everything again. If the PR is approved, I will write tests
=> Added dio options parameter

swagger_parser/lib/src/parser/corrector/open_api_corrector.dart, swagger_parser/test/e2e/e2e_test.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.2.0/expected_files/clients/client_client.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.2.0/expected_files/export.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.2.0/expected_files/models/error_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.2.0/expected_files/models/lizt_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.2.0/expected_files/models/new_pet_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.2.0/expected_files/models/new_pet_dto_action_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.2.0/expected_files/models/pet_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.2.0/expected_files/rest_client.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.2.0/openapi.yaml, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/clients/client_client.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/export.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/class_name1_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/class_name2_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/class_name3_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/class_name56_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/class_name5_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/data1_att_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/data_att2_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/data_att4_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/enum0_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/object0_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/object1_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/p1_class_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/p2_enum_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/private_att_data3_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/models/private_class_name4_dto.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/expected_files/rest_client.dart, swagger_parser/test/e2e/tests/basic/replacement_rules.3.1/openapi.yaml
Issue: https://github.com/Carapacik/swagger_parser/issues/266
Changes: 
- Fix corrector: add "definitions" which is used for models in OpenAPI 2.0 
- Add tests for replacement rules feature
=> Fix replacement rules for OpenAPI 2.0 

swagger_parser/lib/src/parser/parser/open_api_parser.dart
Return empty Map when schema properties is not Map<String, dynamic> type to prevent null safety runtime errors. (#280)
=> fix: return empty Map when schema properties is null

swagger_parser/lib/src/config/swp_config.dart, swagger_parser/lib/src/parser/config/parser_config.dart, swagger_parser/lib/src/parser/parser/open_api_parser.dart, swagger_parser/test/e2e/e2e_test.dart
This PR adds a config parameter to check if the schema is using x-nullable extension or not, if the project is not using then x-nullable is not used in the parser. Without this change, all properties are considered required for Schema that do not use x-nullable.
**This is a breaking change**
=> feat: add config option to know if schema is using x-nullable extension

swagger_parser/lib/src/generator/templates/dart_freezed_dto_template.dart, swagger_parser/test/e2e/tests/basic/discriminated_one_of.3.0/expected_files/models/family_members_union.dart
Fixes #300
Changed the union case class name generation to include the parent class name as prefix to avoid naming conflicts with standalone classes.
```dart
// Before
const factory ResponseItemsUnion.a(...) = ItemA;
// After
const factory ResponseItemsUnion.a(...) = ResponseItemsUnionA;
```
=> Fix discriminator class naming conflicts

swagger_parser/lib/src/generator/templates/dart_dart_mappable_dto_template.dart, swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart, swagger_parser/test/e2e/tests/basic/discriminated_one_of.3.0_mappable/expected_files/models/android_device_type.dart, swagger_parser/test/e2e/tests/basic/discriminated_one_of.3.0_mappable/expected_files/models/cat_type.dart, swagger_parser/test/e2e/tests/basic/discriminated_one_of.3.0_mappable/expected_files/models/dog_type.dart, swagger_parser/test/e2e/tests/basic/discriminated_one_of.3.0_mappable/expected_files/models/human_type.dart, swagger_parser/test/e2e/tests/basic/discriminated_one_of.3.0_mappable/expected_files/models/ios_device_type.dart
Dart Mappable does not generate a toJson method for enums, instead generating a toValue method. There are no plans to change this. API client generators like Retrofit rely on detecting a toJson method to determine whether to use the enums name value or a serialized value.
This commit adds a toJson method to all enums.
`unknownEnumValue` functionality is also implemented fully.
=> dart mappable enums: toJson and default values

swagger_parser/README.md
This changed was introduced in [version 1.16.0](https://pub.dev/packages/swagger_parser/changelog#1160), but the documentation was not updated.
=> fix: Rename `squash_clients` to `merge_clients` on the README

swagger_parser/CHANGELOG.md, swagger_parser/lib/src/generator/templates/dart_typedef_template.dart, swagger_parser/pubspec.yaml, swagger_parser/test/generator/data_classes_test.dart
Fixes `typedefs` being transparent and causing import issues for json_serializable
https://github.com/google/json_serializable.dart/issues/1124
=> typedef_json_serializable_fix

swagger_parser/CHANGELOG.md, swagger_parser/lib/src/parser/parser/open_api_parser.dart, swagger_parser/pubspec.yaml, swagger_parser/test/e2e/tests/basic/all_of.3.0/all_of.3.0.json, swagger_parser/test/e2e/tests/basic/all_of.3.0/expected_files/models/get_users_response.dart
In case of heavily relying on `anyOf` it could result in a mixed stack of different refs and properties there is some chance that combined props will overlap by name.
This PR addresses the issue with deduplicating them by name.
Check test file for deatils
```
"responses":{
"200":{
"description":"",
"content":{
"application/json":{
"schema":{
"allOf":[
{
"$ref":"#/components/schemas/CursorPaginatedDto"
},
{
"properties":{
"data":{
"type":"array",
"items":{
"$ref":"#/components/schemas/UserDto"
}
},
"nextCursor":{
"type":"number",
"nullable":true,
"example":"01AN4Z07BY"
}
},
"required":[
"data",
"nextCursor"
]
}
]
}
}
}
}
},
```
in this case we are redefining `nextCursor` from `CursorPaginatedDto`
```
"nextCursor":{
"type":"string",
"nullable":true,
"example":"01AN4Z07BY"
}
```
with …
=> deduplicate by name

swagger_parser/CHANGELOG.md, swagger_parser/README.md, swagger_parser/lib/src/config/swp_config.dart, swagger_parser/lib/src/generator/config/generator_config.dart, swagger_parser/lib/src/generator/generator/fill_controller.dart, swagger_parser/lib/src/generator/generator/generator_processor.dart, swagger_parser/lib/src/generator/model/programming_language.dart, swagger_parser/lib/src/generator/templates/dart_dart_mappable_dto_template.dart, swagger_parser/lib/src/generator/templates/dart_freezed_dto_template.dart, swagger_parser/lib/src/generator/templates/dart_json_serializable_dto_template.dart, swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart, swagger_parser/lib/src/generator/templates/dart_typedef_template.dart, swagger_parser/lib/src/generator/templates/kotlin_moshi_dto_template.dart, swagger_parser/lib/src/generator/templates/kotlin_retrofit_client_template.dart, swagger_parser/lib/src/generator/templates/kotlin_typedef_template.dart, swagger_parser/lib/src/parser/utils/type_utils.dart, swagger_parser/lib/src/utils/base_utils.dart, swagger_parser/lib/src/utils/type_utils.dart, swagger_parser/pubspec.yaml, swagger_parser/test/generator/rest_clients_test.dart
As far as I can see, this should be the only thing that could prevent using `swagger_parser` to generate clients for use with Flutter on the web.
EDIT: Oh, and it appears `retrofit` [only supports `List<MultipartFile>`](https://github.com/trevorwang/retrofit.dart/issues/464), which is why I used that as the type rather than simply `MultipartFile`
=> Support using MultipartFile instead of File

swagger_parser/README.md
The use of the newly added generator arguments was not correctly documented in the README.
=> doc: fixed documentation on generator arguments

swagger_parser/lib/src/parser/parser/open_api_parser.dart
upon filtering tags map all to lowerCase to allow case insensitive filtering
=> fix: map tags to lowerCase on include or exclude check

swagger_parser/lib/src/parser/parser/open_api_parser.dart, swagger_parser/test/e2e/tests/basic/nullable_discriminator/expected_files/models/test_data_type.dart, swagger_parser/test/e2e/tests/basic/nullable_discriminator/expected_files/models/test_data_type_type.dart, swagger_parser/test/e2e/tests/basic/nullable_discriminator/expected_files/models/test_entity.dart, swagger_parser/test/e2e/tests/basic/nullable_discriminator/expected_files/models/test_entity_data_union.dart, swagger_parser/test/e2e/tests/basic/nullable_discriminator/nullable_discriminator.json
When OpenAPI schemas define discriminated unions (oneOf/anyOf) with `nullable: true`, the generated Dart code incorrectly produces `required Type data` instead of the expected `Type? data`, causing compilation errors.
- Add nullable property handling for discriminated oneOf/anyOf unions
- Set isRequired to false for null-only schemas  
- Add test case for nullable discriminator scenarios
- Fixes issue where nullable discriminator unions were incorrectly generated as required
- Added comprehensive test case in `test/e2e/tests/basic/nullable_discriminator/`
- Test covers nullable discriminator union scenarios
- All existing tests continue to pass
- Verified the fix generates correct `Type? data` syntax
- Code formatted with `dart format .`
- Code analyzed with `dart analyze` - no issues …
=> fix: Handle nullable discriminator unions properly
