Carapacik/swagger_parser

- .github/workflows/gh-pages.yml
- .github/workflows/tests.yml
- README.md
- swagger_parser/CHANGELOG.md
- swagger_parser/README.md
- swagger_parser/analysis_options.yaml
- swagger_parser/bin/generate.dart
- swagger_parser/example/pubspec.yaml
- swagger_parser/lib/src/config/yaml_config.dart
- swagger_parser/lib/src/generator/generator.dart
- swagger_parser/lib/src/generator/models/programming_lang.dart
- swagger_parser/lib/src/generator/models/universal_component_class.dart
- swagger_parser/lib/src/generator/models/universal_data_class.dart
- swagger_parser/lib/src/generator/models/universal_enum_class.dart
- swagger_parser/lib/src/generator/models/universal_type.dart
- swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart
- swagger_parser/lib/src/generator/templates/dart_freezed_dto_template.dart
- swagger_parser/lib/src/generator/templates/dart_json_serializable_dto_template.dart
- swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
- swagger_parser/lib/src/generator/templates/kotlin_enum_dto_template.dart
- swagger_parser/lib/src/generator/templates/kotlin_moshi_dto_template.dart
- swagger_parser/lib/src/parser/parser.dart
- swagger_parser/lib/src/utils/case_utils.dart
- swagger_parser/lib/src/utils/type_utils.dart
- swagger_parser/pubspec.yaml
- swagger_parser/test/generator/data_classes_test.dart
- swagger_parser/test/generator/rest_clients_test.dart
- Add support for ` default ` annotations
- Add enum support for dart
- Fixed errors with Multipart
- Fixed errors with Kotlin types
- Add format for ci
> 0.4.0 Default value and enum

- swagger_parser/CHANGELOG.md
- swagger_parser/README.md
- swagger_parser/example/pubspec.yaml
- swagger_parser/lib/src/generator/models/universal_type.dart
- swagger_parser/lib/src/generator/templates/dart_json_serializable_dto_template.dart
- swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
- swagger_parser/lib/src/parser/parser.dart
- swagger_parser/pubspec.yaml
- swagger_parser/test/generator/data_classes_test.dart
> Closes #32 Skip parsing of servers property

- swagger_parser/lib/swagger_parser.dart
Export parser, so it can be used within other projects.
> Export parser

- swagger_parser/CHANGELOG.md
- swagger_parser/README.md
- swagger_parser/lib/src/config/yaml_config.dart
- swagger_parser/lib/src/generator/generator.dart
- swagger_parser/lib/src/generator/models/universal_request.dart
- swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
- swagger_parser/lib/src/parser/parser.dart
- swagger_parser/pubspec.yaml
> Add an option for generating http response

- swagger_parser/CHANGELOG.md
- swagger_parser/lib/src/parser/parser.dart
- swagger_parser/pubspec.yaml
Reverts Carapacik/swagger_parser#117
> Revert "Fix bug when additionalProperties has ref."

- swagger_parser/lib/src/parser/parser.dart
> Fix error when additionalProperties has ref

- swagger_parser/CHANGELOG.md
- swagger_parser/lib/src/parser/parser.dart
- swagger_parser/pubspec.yaml
- swagger_parser/test/parser/data_classses_test.dart
- swagger_parser/test/parser/schemas/additional_properties_class.3.0.json
fixed object with additionalProperties which is not meant to be parsed as an object still parsing into one
> 1.10.6 non-object-additionalProperties

- swagger_parser/lib/src/parser/parser.dart
#123 is a wrong commit because my test case has a mistake.
> Revert #123

- swagger_parser/CHANGELOG.md
- swagger_parser/pubspec.yaml
Sorry I forgot to update the changelog and pubspec version for the previous [Pull Request](https://github.com/Carapacik/swagger_parser/pull/133)
> chore: updated changelog and version

- swagger_parser/CHANGELOG.md
- swagger_parser/lib/src/generator/models/universal_enum_class.dart
- swagger_parser/lib/src/parser/parser.dart
- swagger_parser/pubspec.yaml
- swagger_parser/test/parser/data_classses_test.dart
> fix: generating enum unique name

- swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
If type is List<File> it didn't import io.
> Upgrade 'dart:io' import logic

- swagger_parser/lib/src/generator/templates/dart_dart_mappable_dto_template.dart
- swagger_parser/test/generator/data_classes_test.dart
Add MappableField when jsonkey is different then name (dart_mappable)
> Add MappableField

- swagger_parser/CHANGELOG.md
- swagger_parser/lib/src/parser/utils/type_utils.dart
- swagger_parser/pubspec.yaml
- swagger_parser/test/generator/data_classes_test.dart
- swagger_parser_pages/lib/content/information_box.dart
The swagger_parser lacked support for Int64, which is crucial for a project I'm working on. I've added the implementation and a test to make sure everything works as expected.
> Added support for Int64

- swagger_parser/lib/src/parser/parser/open_api_parser.dart
- swagger_parser/test/e2e/tests/basic/of_like_class.3.1/expected_files/models/one_of_element.dart
- swagger_parser/test/e2e/tests/basic/of_like_class.3.1/of_like_class.3.1.json
- swagger_parser/test/e2e/tests/nullable_types/expected_files/models/class_with_nullable_types.dart
- swagger_parser/test/e2e/tests/nullable_types/openapi.yaml
> fix: read nullable property from anyOf types

- swagger_parser/lib/src/parser/parser/open_api_parser.dart
- swagger_parser/test/e2e/e2e_test.dart
- swagger_parser/test/e2e/tests/nullable_types.2.0/expected_files/clients/pet_client.dart
- swagger_parser/test/e2e/tests/nullable_types.2.0/expected_files/export.dart
- swagger_parser/test/e2e/tests/nullable_types.2.0/expected_files/models/category.dart
- swagger_parser/test/e2e/tests/nullable_types.2.0/expected_files/models/pet.dart
- swagger_parser/test/e2e/tests/nullable_types.2.0/expected_files/models/pet_status.dart
- swagger_parser/test/e2e/tests/nullable_types.2.0/expected_files/models/status_status.dart
- swagger_parser/test/e2e/tests/nullable_types.2.0/expected_files/rest_client.dart
- swagger_parser/test/e2e/tests/nullable_types.2.0/swagger.yaml
Issue: https://github.com/Carapacik/swagger_parser/issues/268
> feat: Add “x-nullable” field for null definition in OpenAPI 2.0

- swagger_parser/lib/src/config/swp_config.dart
> Fix: config properties inheritance with multi-scheme urls

- swagger_parser/lib/src/config/swp_config.dart
Fixes both https://github.com/Carapacik/swagger_parser/issues/296 and https://github.com/Carapacik/swagger_parser/issues/293
> Fix multi-scheme config parse

- swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart
- swagger_parser/lib/src/parser/utils/type_utils.dart
- swagger_parser/test/e2e/e2e_test.dart
- swagger_parser/test/e2e/tests/enum_types_list/expected_files/clients/api_client.dart
- swagger_parser/test/e2e/tests/enum_types_list/expected_files/export.dart
- swagger_parser/test/e2e/tests/enum_types_list/expected_files/models/enum_class.dart
- swagger_parser/test/e2e/tests/enum_types_list/expected_files/models/enum_class_dynamic.dart
- swagger_parser/test/e2e/tests/enum_types_list/expected_files/rest_client.dart
- swagger_parser/test/e2e/tests/enum_types_list/openapi.yaml
> Add support for type list with enum

- swagger_parser/CHANGELOG.md
- swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
- swagger_parser/lib/src/utils/type_utils.dart
- swagger_parser/pubspec.yaml
- swagger_parser/test/e2e/e2e_test.dart
- swagger_parser/test/e2e/tests/basic/query_parameters/expected_files/clients/client_client.dart
- swagger_parser/test/e2e/tests/basic/query_parameters/expected_files/export.dart
- swagger_parser/test/e2e/tests/basic/query_parameters/expected_files/models/pet.dart
- swagger_parser/test/e2e/tests/basic/query_parameters/expected_files/rest_client.dart
- swagger_parser/test/e2e/tests/basic/query_parameters/openapi.yaml
- swagger_parser/test/e2e/tests/enum_types_list/expected_files/clients/api_client.dart
- swagger_parser/test/e2e/tests/enum_types_list/expected_files/export.dart
- swagger_parser/test/e2e/tests/enum_types_list/expected_files/models/credential_types.dart
- swagger_parser/test/e2e/tests/enum_types_list/openapi.yaml
- swagger_parser/test/generator/data_classes_test.dart
- swagger_parser/test/generator/rest_clients_test.dart
> fix for issues/335

- swagger_parser/CHANGELOG.md
- swagger_parser/README.md
- swagger_parser/lib/src/parser/utils/type_utils.dart
- swagger_parser/pubspec.yaml
- swagger_parser/test/generator/rest_clients_test.dart
Fixes https://github.com/Carapacik/swagger_parser/issues/340
> Allow using single Multipart file arguments

- swagger_parser/CHANGELOG.md
- swagger_parser/README.md
- swagger_parser/lib/src/config/swp_config.dart
- swagger_parser/lib/src/generator/config/generator_config.dart
- swagger_parser/lib/src/generator/generator/fill_controller.dart
- swagger_parser/lib/src/generator/generator/generator.dart
- swagger_parser/lib/src/generator/model/programming_language.dart
- swagger_parser/lib/src/generator/templates/dart_dart_mappable_dto_template.dart
- swagger_parser/lib/src/generator/templates/dart_enum_dto_template.dart
- swagger_parser/lib/src/generator/templates/dart_export_file_template.dart
- swagger_parser/lib/src/generator/templates/dart_freezed_dto_template.dart
- swagger_parser/lib/src/generator/templates/dart_json_serializable_dto_template.dart
- swagger_parser/lib/src/generator/templates/dart_retrofit_client_template.dart
- swagger_parser/lib/src/generator/templates/dart_root_client_template.dart
- swagger_parser/lib/src/generator/templates/dart_typedef_template.dart
- swagger_parser/lib/src/generator/templates/kotlin_enum_dto_template.dart
- swagger_parser/lib/src/generator/templates/kotlin_moshi_dto_template.dart
- swagger_parser/lib/src/generator/templates/kotlin_retrofit_client_template.dart
- swagger_parser/lib/src/generator/templates/kotlin_typedef_template.dart
- swagger_parser/lib/src/utils/base_utils.dart
- swagger_parser/test/e2e/e2e_test.dart
- swagger_parser/test/e2e/tests/basic/merged_outputs/expected_files/merged_outputs.dart
- swagger_parser/test/e2e/tests/basic/merged_outputs/merged_outputs.json
This will make it a lot easier to write a reliable builder for build_runner.
Reopening of https://github.com/Carapacik/swagger_parser/pull/349
> Allow merging all outputs into a single file
